# *****Apple vs Orange Classification*****

### Import Libraries and Model

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

#### Load dataset

In [2]:
df=pd.read_csv(r"C:\Users\Yuvraj Bhavsar\OneDrive\Desktop\csv file\Apple_vs_Orange_Dataset.csv")
df.head()

       Weight     Color  Label
0  187.454012  0.015715  Apple
1  245.071431  0.318205  Apple
2  223.199394  0.157178  Apple
3  209.865848  0.254285  Apple
4  165.601864  0.453783  Apple

In [3]:
df.tail()

        Weight     Color   Label
95  149.379560  0.674605  Orange
96  152.273283  0.862978  Orange
97  142.754102  0.948555  Orange
98  102.541913  0.943543  Orange
99  110.789143  0.889938  Orange

#### **Weight** : The weight of the fruit (150-250g for apples, 100-200g for oranges).

#### **Color** : A numerical representation (closer to 0 for apples, closer to 1 for oranges).

#### **Label** : The output feature ("Apple" or "Orange").

In [4]:
df.shape

(100, 3)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Weight  100 non-null    float64
 1   Color   100 non-null    float64
 2   Label   100 non-null    object
dtypes: float64(2), object(1)
memory usage: 2.5+ KB

In [6]:
LE = LabelEncoder()
df['Label'] = LE.fit_transform(df['Label'])  # for [apple 0] and [orange 1]

In [7]:
df.head()

       Weight     Color  Label
0  187.454012  0.015715      0
1  245.071431  0.318205      0
2  223.199394  0.157178      0
3  209.865848  0.254285      0
4  165.601864  0.453783      0

In [8]:
df.tail()

        Weight     Color  Label
95  149.379560  0.674605      1
96  152.273283  0.862978      1
97  142.754102  0.948555      1
98  102.541913  0.943543      1
99  110.789143  0.889938      1

## Apply KNN model

In [9]:
X = df.drop(columns=['Label'])
y = df['Label']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
print(f"Training set shape: {X_train.shape}")
print(f"Testing set shape: {X_test.shape}")

Training set shape: (80, 2)
Testing set shape: (20, 2)

In [12]:
best_k = 1
best_accuracy = 0
accuracies = []

for k in range(1, 35):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred_test = knn.predict(X_test)
    
    accuracy_test = accuracy_score(y_test, y_pred_test)
    accuracies.append((k, accuracy_test))  
    
    if accuracy_test > best_accuracy:
        best_k = k
        best_accuracy = accuracy_test

### **Classification Report**

In [14]:
# Train model again using best_k
knn_best = KNeighborsClassifier(n_neighbors=best_k)
knn_best.fit(X_train, y_train)

# Prediction using best model
y_pred_test_best = knn_best.predict(X_test)

In [15]:
print(f"Classification Report for k = {best_k}")
print(classification_report(y_test, y_pred_test_best, target_names=["Apple", "Orange"]))

Classification Report for k = 11
              precision    recall  f1-score   support

       Apple       1.00      0.75      0.86        12
      Orange       0.73      1.00      0.84         8

    accuracy                           0.85        20
   macro avg       0.86      0.88      0.85        20
weighted avg       0.89      0.85      0.85        20

### ***Let's check the 'k values vs accuracies'***

In [ ]:
k_values = [acc[0] for acc in accuracies]
test_accuracies = [acc[1] for acc in accuracies]
plt.figure(figsize=(8, 5))
plt.plot(k_values, test_accuracies, marker='o', linestyle='-')
plt.title("K Value vs Accuracy")
plt.xlabel("K Values")
plt.ylabel("Accuracy")
plt.xticks(range(1, 36, 2))  
plt.grid()
plt.show()

In [ ]:
print(f"Best k value: {best_k} with accuracy: {best_accuracy:.2f}")

### *for k= [ 11, 12, 24, 27, 28] Accuracy is high*

In [ ]:
import numpy as np
new_weight = 175
new_color = 0.301023

In [ ]:
new_weight = 175
new_color = 0.301023
new_data_point = np.array([[new_weight, new_color]])
predicted_label = knn.predict(new_data_point)
predicted_label

### for new datapoints [new_weight = 175 new_color = 0.301023] output is '0' means that new fruit is apple

### **Let's make plot for this new data point prediction**

In [ ]:
plt.figure(figsize=(8, 5))
plt.scatter(X_train['Weight'][y_train == 0], X_train['Color'][y_train == 0], color='blue', label='Apple', marker='o')
plt.scatter(X_train['Weight'][y_train == 1], X_train['Color'][y_train == 1], color='orange', label='Orange', marker='x')
plt.scatter(new_weight, new_color, color='green', label=f'New Data Point ({predicted_label[0]})', marker='^', s=100)
plt.title('KNN Prediction for New Data Point')
plt.xlabel('Weight')
plt.ylabel('Color (Encoded)')
plt.legend()
plt.grid(True)
plt.show()

### **Confusion Matrix**

In [ ]:
knn_best = KNeighborsClassifier(n_neighbors=best_k)
knn_best.fit(X_train, y_train)
y_pred_test_best = knn_best.predict(X_test)
cm = confusion_matrix(y_test, y_pred_test_best)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["Apple", "Orange"])
disp.plot(cmap=plt.cm.Blues)
plt.title(f"Confusion Matrix for k = {best_k}")
plt.show()

# ***Conclusion***
#### The KNN algorithm effectively classified fruits as "Apple" or "Orange" based on their Weight and Color. The best performance was achieved by selecting the optimal k value, which was determined through testing various values. Overall, the model provided accurate predictions.